// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDi8pvq4y2GIBgnH-S-4LQmgFIwHbrN-I',
    appId: '1:480060936646:web:432c82560fcd7d86a6e2c7',
    messagingSenderId: '480060936646',
    projectId: 'portfolio-nguyenthe',
    authDomain: 'portfolio-nguyenthe.firebaseapp.com',
    storageBucket: 'portfolio-nguyenthe.firebasestorage.app',
    measurementId: 'G-LG2XLVQKJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClYMr7Dfazl8ME7gSts4M7gTQBNfBrCKo',
    appId: '1:480060936646:android:cac9d86fe01c71f8a6e2c7',
    messagingSenderId: '480060936646',
    projectId: 'portfolio-nguyenthe',
    storageBucket: 'portfolio-nguyenthe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTNbmyyU9UTxB9tVPeER7zb6jZ9mh10N0',
    appId: '1:480060936646:ios:93ef3807a498d181a6e2c7',
    messagingSenderId: '480060936646',
    projectId: 'portfolio-nguyenthe',
    storageBucket: 'portfolio-nguyenthe.firebasestorage.app',
    iosBundleId: 'com.example.simpleJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTNbmyyU9UTxB9tVPeER7zb6jZ9mh10N0',
    appId: '1:480060936646:ios:93ef3807a498d181a6e2c7',
    messagingSenderId: '480060936646',
    projectId: 'portfolio-nguyenthe',
    storageBucket: 'portfolio-nguyenthe.firebasestorage.app',
    iosBundleId: 'com.example.simpleJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVbl6QaJKmKmHOALU9anGKOcIOULFVNh8',
    appId: '1:480060936646:web:621aabbc7077ae57a6e2c7',
    messagingSenderId: '480060936646',
    projectId: 'portfolio-nguyenthe',
    authDomain: 'portfolio-nguyenthe.firebaseapp.com',
    storageBucket: 'portfolio-nguyenthe.firebasestorage.app',
    measurementId: 'G-JLSF5T5SWC',
  );

}